### PR TITLE
Add frontend views

### PR DESCRIPTION
**Pull request by angelocordon**
Add dashboard front end views using Boostrap + React 
Handle: #30 #31

### CODE REVIEW

**Comment by stain88** [comment]
Curious, any reason why you're not using a [bootstrap gem](https://github.com/twbs/bootstrap-rubygem) instead of hard-coding the bootstrap dependencies?

**Comment by angelocordon** [comment]
Great comment @stain88 - I'll most likely move on to the gem eventually; for now since I'm not positive on our front end strategies yet, I thought this would be easiest to implement and take out. Plus, gives us the benefits of cached assets through CDN.

**Review by jesperhodge — CHANGES_REQUESTED** [review]
Your code looks good so far.

[Note for future issue: Can we import the Navbar higher up the component chain? I assume the Navbar buttons will lead to different pages later. So If we put the Navbar outside of the component that does the routes (App.jsx) then it is not loaded fresh for every page, which is really good.

So inside the hello_react.jsx (which we really need to rename :D ):
`<BrowserRouter>
       <DashboardNavbar />
	<App />
</BrowserRouter>,
`
]

The only problem is that you pull in standard bootstrap which uses jQuery, and jQuery manipulates the DOM directly, which is considered extremely bad practice. (https://stackoverflow.com/questions/40037657/how-to-include-bootstrap-css-and-js-in-reactjs-app, second anser;https://www.quora.com/Why-do-we-need-React-Bootstrap-when-we-can-use-Bootstrap-in-the-React-app-What-are-the-benefits-of-React-Bootstrap-Id-prefer-to-use-the-original-because-I-want-to-use-Bootstrap-4). I strongly recommend https://github.com/reactstrap/reactstrap together with the bootstrap component for npm/yarn.

To prevent a lot of future bugs or code not working for other collaborators when they want to build something, please switch to ReactStrap.

**Comment by angelocordon** [comment]
// 🚲shed:

@Aliin I don't disagree, DOM manipulation is typically considered an anti pattern these days and can be, in some cases, expensive memory-wise. However, none of the links you provided explains why it's "considered extremely bad practice" (unless I totally missed it?). The most helpful answers I've found are stuck all the way down at the bottom of the Quora link: 

> Bootstrap uses its own javascript which may conflict with react rendering of virtual dom... When react tries to render the dom its invokes external javascripts like material js or bootstrap js which causes extra overhead and can slow down the web app if it is content heavy.
Using react components gives the developers the assurance that there wont be external calls to javascripts which might be incompatible with react dom renderer.
[Quora Answer](https://www.quora.com/Why-do-we-need-React-Bootstrap-when-we-can-use-Bootstrap-in-the-React-app-What-are-the-benefits-of-React-Bootstrap-Id-prefer-to-use-the-original-because-I-want-to-use-Bootstrap-4/answer/Saurabh-Mhatre-7)

> I am not sure you can actually use pure Bootstrap with React because I believe the Javascript in Bootstrap may manipulate the DOM and that would cause problems for React and how it detect changes and updates the DOM.
[Quora Answer](https://www.quora.com/Why-do-we-need-React-Bootstrap-when-we-can-use-Bootstrap-in-the-React-app-What-are-the-benefits-of-React-Bootstrap-Id-prefer-to-use-the-original-because-I-want-to-use-Bootstrap-4/answer/Ashley-Aitken)

All in all, I think it just depends™. 

But will check out ReactStrap though.

**Review by jesperhodge — APPROVED** [review]

**Comment by jesperhodge** [comment]
I would still like us to switch to Reactstrap right away but I'm for merging this and doing all of that in a followup issue.

**Comment by jesperhodge** [comment]
## Merging Checklist:
- [x] open an issue to switch to Reactstrap

**Pull request merged**
